### ISSUE TITLE
你好，Phase1/cn_training_set_rel1.tsv  这个文件是怎么生成的

### ISSUE THREAD

**Issue by rongyousu** [shibing624/judger#1]
public static String CNTrainSetPath = "Phase1/cn_training_set_rel1.tsv

**Comment by shibing624** [comment]
我自己制作的，写爬虫爬取的小学生各年级作文

**Comment by rongyousu** [comment]
你好，作文评分是哪一个代码？  最后生成的 .arff文件里面我该如何理解
文件后面的 @data部分是各个特征模块的权重吗?  文章的最后评价分数是怎么获取呢？谢谢！

**Comment by shibing624** [comment]
.arff 里面的内容是各特征值，这个文件可以直接对接weka处理，weka是一个机器学习开源包。之后我会完善词程序，写一个小学生作文评分的接口及实例，正在开发。。。
